[metadata]
name = pymayhem
version = 0.1.0
description = Standalone Python API for Mayhem firmware serial control
python_requires = >=3.10

[options]
packages = find:
install_requires =
    pyserial>=3.5

[options.packages.find]
where = .
include = pymayhem*

[options.extras_require]
test =
    pytest
